apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Env.BENCH_NAME }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: avalanche
  namespace: {{ .Env.BENCH_NAME }}
  labels:
    app: avalanche
spec:
  selector:
    matchLabels:
      app: avalanche
  replicas: 16
  template:
    metadata:
      labels:
        app: avalanche
    spec:
      containers:
      - name: avalanche
        image: gcr.io/gpe-test-1/avalanche:v0.6.0-main-bw6 #quay.io/prometheuscommunity/avalanche:main
        args:
        # Aim for 10k series target with realistic distribution of types.
        # Captured exampleprometheustarget.txt from an example Prometheus /metric page.
        # Then generated (and adjusted a bit) below flags using:
        # cd tools/mtypes && cat ../../manifests/load/exampleprometheustarget.txt | go run main.go --avalanche-flags-for-adjusted-series=10000
        - "--gauge-metric-count=158"
        - "--counter-metric-count=280"
        - "--histogram-metric-count=28"
        - "--histogram-metric-bucket-count=10" # Does not count +Inf
        - "--native-histogram-metric-count=0"
        - "--summary-metric-count=48" # One metric gives 2 series.
        - "--summary-metric-objective-count=2" # One metric gives 2 series.
        - "--series-count=10"
        - "--value-interval=300" # Changes values every 5m
        - "--series-interval=3600" # 1h series churn.
        - "--metric-interval=0"
        - "--port=9001"
        ports:
        - containerPort: 9001
          name: metrics
      nodeSelector:
        role: {{ .Env.BENCH_NAME }}-work
