name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit tests on Go ${{ matrix.go }} ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.x'
    - uses: actions/cache@v3
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
    - name: Run unit tests.
      env:
        GOBIN: /tmp/.bin
      run: make test
