---
name: golangci-lint
on:
  push:
    paths:
    - "**.go"
    - "scripts/errcheck_excludes.txt"
    - ".github/workflows/golangci-lint.yml"
    - ".golangci.yml"

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

env:
  GO_VERSION: stable
  GOLANGCI_LINT_VERSION: v1.60

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: golangci-lint mtypes
      uses: golangci/golangci-lint-action@v6
      with:
        version: ${{ env.GOLANGCI_LINT_VERSION }}
        working-directory: ./tools/mtypes
